baseURL = "https://deepvalue.space/"
languageCode = "en-us"
title = "DeepValue"
description = "mingxuan's blog"
theme = ["bear-style"]

# 分类配置
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  mainSections = ["posts"]
  description = "Searching for Asymmetry in Markets"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 2